language: python

python:
  - "3.8"
install:
  - pip install -r requirements.txt
script:
  - flake8 ./app
#  - pytest app/tests/ --cov=app --cov-report html && coverage report --fail-under=80
  - python app/manage.py makemigrations --check --dry-run
