version: "3.7"

services:
  backend:
    command: python ./app/manage.py runserver 0:8000
    volumes:
      - "./:/home/prod"
    ports:
      - "8000:8000"
      - "8001:8001"

  memcached:
    ports:
      - "11211:11211"

  rabbitmq:
    ports:
      - "15672:15672"

  postgres:
    image: postgres:13.4-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: {}