version: "3.7"

services:
  memcached:
    image: memcached
    container_name: memcached
    ports:
      - "11211:11211"
#    env_file:
#      - .env

  rabbitmq:
    image: rabbitmq:3.8
    container_name: rabbitmq
    ports:
      - "5672:5672"
    env_file:
      - .env

  postgres:
    image: postgres:13.4-alpine
    container_name: postgres
    ports:
      - "5432:5432"
#    environment:
#      - POSTGRES_PASSWORD=123456
#      - POSTGRES_USER=test_user
#      - POSTGRES_DB=database_name
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: {}