CODE_NAME_PRIVATBANK = 'privatbank'
CODE_NAME_MONOBANK = 'monobank'
CODE_NAME_VKURSE = 'vkurse.dp.ua'
CODE_NAME_OSCHADBANK = 'oschadbank'
CODE_NAME_ALFABANK = 'alfabank'
CODE_NAME_RAIFFEISEN = 'raiffeisen'
