# Generated by Django 3.2.3 on 2021-07-18 11:20

from django.db import migrations


def forwards(apps, schema_editor):
    Source = apps.get_model('currency', 'Source')

    for source in Source.objects.all():
        if 'privatbank' not in source.code_name.lower():
            Source.objects.create(
                name='PrivatBank',
                code_name='privatbank',
                url='https://api.privatbank.ua/p24api/pubinfo?json&exchange&coursid=5',
                original_url='https://privatbank.ua/',
                phone='3700'
            )
        elif 'monobank' not in source.code_name.lower():
            Source.objects.create(
                name='MonoBank',
                code_name='monobank',
                url='https://api.monobank.ua/bank/currency',
                original_url='https://www.monobank.ua/',
                phone='0 800 205 205'
            )
        elif 'vkurse.dp.ua' not in source.code_name.lower():
            Source.objects.create(
                name='Vkurse',
                code_name='vkurse.dp.ua',
                url='http://vkurse.dp.ua/course.json',
                original_url='http://vkurse.dp.ua/',
                phone='+38(067)989-22-95'
            )
        elif 'oschadbank' not in source.code_name.lower():
            Source.objects.create(
                name='OschadBank',
                code_name='oschadbank',
                url='https://www.oschadbank.ua/ua',
                original_url='https://www.oschadbank.ua/ua',
                phone='0 800 210 800'
            )
        elif 'alfabank' not in source.code_name.lower():
            Source.objects.create(
                name='AlfaBank',
                code_name='alfabank',
                url='https://alfabank.ua/',
                original_url='https://alfabank.ua/',
                phone='3344'
            )
        elif 'raiffeisen' not in source.code_name.lower():
            Source.objects.create(
                name='RaiffeisenBank',
                code_name='raiffeisen',
                url='https://raiffeisen.ua/',
                original_url='https://raiffeisen.ua/',
                phone='0 800 500 500'
            )

        source.save()


def backwards(apps, schema_editor):
    print('HELLO FROM BACKWARDS') # noqa


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
