# Generated by Django 3.2.3 on 2021-07-18 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0002_auto_20210718_1120'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='analytics',
            unique_together={('path', 'request_method', 'status')},
        ),
    ]
