# Generated by Django 3.2.3 on 2021-05-24 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0002_contactus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rate',
            old_name='type',
            new_name='cur_type',
        ),
    ]
