# Generated by Django 3.2.3 on 2021-05-25 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0003_rename_type_rate_cur_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='subject',
            field=models.CharField(max_length=12),
        ),
    ]
