# Generated by Django 3.2.3 on 2021-08-18 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0004_source_source_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analytics',
            name='request_method',
            field=models.PositiveSmallIntegerField(choices=[
                (10, 'GET'),
                (11, 'POST'),
                (12, 'PUT'),
                (13, 'PATCH'),
                (14, 'DELETE')
            ]
            ),
        ),
    ]
