# Generated by Django 3.2.3 on 2021-08-18 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0005_alter_analytics_request_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
