# Generated by Django 3.2.3 on 2021-06-15 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0006_auto_20210615_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
