# Generated by Django 3.2.3 on 2021-07-06 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0007_alter_source_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='cur_type_new',
            field=models.PositiveSmallIntegerField(choices=[(10, 'Dollar'), (11, 'Euro')], default=10),
        ),
    ]
