# Generated by Django 3.2.3 on 2021-07-06 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0008_rate_cur_type_new'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='cur_type_new',
            field=models.PositiveSmallIntegerField(choices=[(10, 'Dollar'), (11, 'Euro')], default=222),
        ),
    ]
