# Generated by Django 3.2.3 on 2021-07-07 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0010_auto_20210706_2028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rate',
            name='cur_type',
        ),
    ]
