# Generated by Django 3.2.3 on 2021-07-07 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0011_remove_rate_cur_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rate',
            name='cur_type_new',
        ),
        migrations.AddField(
            model_name='rate',
            name='cur_type',
            field=models.PositiveSmallIntegerField(choices=[(10, 'Dollar'), (11, 'Euro')], default=0),
            preserve_default=False,
        ),
    ]
