# Generated by Django 3.2.3 on 2021-07-10 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0014_auto_20210710_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='analytics',
            name='request_method',
            field=models.PositiveSmallIntegerField(choices=[(10, 'GET'), (11, 'POST')], default=1),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='analytics',
            unique_together={('path', 'request_method')},
        ),
    ]
