# Generated by Django 3.2.3 on 2021-07-12 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0015_auto_20210710_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='original_url',
            field=models.URLField(default=True, max_length=255, null=True),
        ),
    ]
