# Generated by Django 3.2.3 on 2021-07-12 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0016_source_original_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='original_url',
            field=models.URLField(max_length=255),
        ),
    ]
