# Generated by Django 3.2.3 on 2021-07-12 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0017_alter_source_original_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='bank',
            field=models.ForeignKey(default=None, null=True,
                                    on_delete=django.db.models.deletion.CASCADE, to='currency.source'),
        ),
    ]
