# Generated by Django 3.2.3 on 2021-07-12 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0019_auto_20210712_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='currency.source'),
        ),
    ]
