# Generated by Django 3.2.3 on 2021-07-13 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0021_auto_20210713_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='code_name',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
