# Generated by Django 3.2.3 on 2021-07-13 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0022_alter_source_code_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rate',
            name='source',
        ),
    ]
